language: ruby
before_install:
- openssl aes-256-cbc -K $encrypted_fdddf752110a_key -iv $encrypted_fdddf752110a_iv
  -in test/config.yml.enc -out test/config.yml -d
- openssl aes-256-cbc -K $encrypted_fdddf752110a_key -iv $encrypted_fdddf752110a_iv
  -in test/config.yml.env -out test/config.yml -d
- gem install bundler
rvm:
- 1.9.3-p551
- 2.0.0-p598
- 2.1.5
- 2.2.0
