# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "remailer"
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Scott Tadman"]
  s.date = "2013-04-05"
  s.description = "EventMachine SMTP Mail User Agent"
  s.email = "scott@twg.ca"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/remailer.rb",
    "lib/remailer/abstract_connection.rb",
    "lib/remailer/constants.rb",
    "lib/remailer/email_address.rb",
    "lib/remailer/imap.rb",
    "lib/remailer/imap/client.rb",
    "lib/remailer/imap/client/interpreter.rb",
    "lib/remailer/imap/server.rb",
    "lib/remailer/imap/server/interpreter.rb",
    "lib/remailer/interpreter.rb",
    "lib/remailer/interpreter/state_proxy.rb",
    "lib/remailer/smtp.rb",
    "lib/remailer/smtp/client.rb",
    "lib/remailer/smtp/client/interpreter.rb",
    "lib/remailer/smtp/server.rb",
    "lib/remailer/smtp/server/interpreter.rb",
    "lib/remailer/smtp/server/transaction.rb",
    "lib/remailer/socks5.rb",
    "lib/remailer/socks5/client.rb",
    "lib/remailer/socks5/client/interpreter.rb",
    "lib/remailer/support.rb",
    "remailer.gemspec",
    "test/config.example.rb",
    "test/helper.rb",
    "test/unit/remailer_imap_client_interpreter_test.rb",
    "test/unit/remailer_imap_client_test.rb",
    "test/unit/remailer_interpreter_state_proxy_test.rb",
    "test/unit/remailer_interpreter_test.rb",
    "test/unit/remailer_smtp_client_interpreter_test.rb",
    "test/unit/remailer_smtp_client_test.rb",
    "test/unit/remailer_smtp_server_test.rb",
    "test/unit/remailer_socks5_client_interpreter_test.rb",
    "test/unit/remailer_test.rb"
  ]
  s.homepage = "http://github.com/twg/remailer"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Reactor-Ready SMTP Mailer"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0"])
  end
end

